---
- name: Add app key
  apt_key:
    url: "http://shutter-project.org/shutter-ppa.key"
    state: present

- name: Add shutter xenial PPA repository
  apt_repository:
    repo: deb http://ppa.launchpad.net/shutter/ppa/ubuntu xenial main
    state: present
